// demo/src/components/CounterDemo.tsx
import React from 'react';
import { count, step, doubled } from '../store';
import { useSignalValue } from '../hooks/useSignal';

export function CounterDemo() {
  const c = useSignalValue(count);
  const s = useSignalValue(step);
  const d = useSignalValue(doubled);

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: '0.5rem', marginBottom: '0.75rem' }}>
        <span style={{ fontSize: '2rem', fontWeight: 'bold' }}>{c}</span>
        <span style={{ color: '#888' }}>doubled: {d}</span>
      </div>
      <div style={{ display: 'flex', gap: '0.4rem', marginBottom: '0.5rem' }}>
        <button onClick={() => count.set(c - s)}>−{s}</button>
        <button onClick={() => count.set(0)}>Reset</button>
        <button onClick={() => count.set(c + s)}>+{s}</button>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
        <span>step:</span>
        <button onClick={() => step.set(s - 1)}>−</button>
        <span style={{ minWidth: '1.5rem', textAlign: 'center' }}>{s}</span>
        <button onClick={() => step.set(s + 1)}>+</button>
      </div>
    </div>
  );
}

// demo/stencil-src/components/counter-demo/counter-demo.tsx
import { Component, Mixin, h } from '@stencil/core';
import { SignalWatcher } from '@kurtaqui/stencil-signals';
import { count, step, doubled } from '../../store';

@Component({ tag: 'counter-demo', shadow: false })
export class CounterDemo extends Mixin(SignalWatcher) {
	render() {
		const c = count();
		const s = step();
		return (
			<div>
				<div style={{ display: 'flex', gap: '1.5rem', marginBottom: '0.75rem', alignItems: 'baseline' }}>
					<span style={{ fontSize: '2rem', fontWeight: 'bold' }}>{c}</span>
					<span style={{ color: '#555' }}>doubled: <strong>{doubled()}</strong></span>
				</div>
				<div style={{ display: 'flex', gap: '0.4rem', alignItems: 'center', marginBottom: '0.5rem' }}>
					<button onClick={() => count.set(c - s)}>−{s}</button>
					<button onClick={() => count.set(0)}>Reset</button>
					<button onClick={() => count.set(c + s)}>+{s}</button>
				</div>
				<div style={{ display: 'flex', gap: '0.4rem', alignItems: 'center', fontSize: '0.85em' }}>
					<label>step:
						<input
							type="number"
							value={s}
							min={1}
							style={{ width: '4rem', marginLeft: '0.4rem' }}
							onInput={(e) => step.set(Number((e.target as HTMLInputElement).value))}
						/>
					</label>
				</div>
			</div>
		);
	}
}
