// demo/stencil-src/components/watch-explicit-demo/watch-explicit-demo.tsx
import { Component, Mixin, h } from '@stencil/core';
import { SignalWatcher, signal, watchEffect } from '@kurtaqui/stencil-signals';

@Component({ tag: 'watch-explicit-demo', shadow: false })
export class WatchExplicitDemo extends Mixin(SignalWatcher) {

	readonly a = signal(2);
	readonly b = signal(3);
	readonly log = signal<string[]>([]);

	connectedCallback(): void {
		super.connectedCallback?.();
		watchEffect([this.a, this.b], ([av, bv]) => {
			this.log.set([...this.log.get(), `${av} × ${bv} = ${av * bv}`].slice(-5));
			return () => console.log('[watch-explicit-demo] watchEffect disposed');
		});
	}

	render() {
		const av = this.a.get();
		const bv = this.b.get();
		const entries = this.log.get();
		return (
			<div>
				<div style={{ display: 'flex', gap: '1rem', marginBottom: '0.75rem', alignItems: 'center' }}>
					<label>
						a:{' '}
						<input
							type="number"
							value={av}
							style={{ width: '4rem', marginLeft: '0.3rem' }}
							onInput={(e) => this.a.set(Number((e.target as HTMLInputElement).value))}
						/>
					</label>
					<label>
						b:{' '}
						<input
							type="number"
							value={bv}
							style={{ width: '4rem', marginLeft: '0.3rem' }}
							onInput={(e) => this.b.set(Number((e.target as HTMLInputElement).value))}
						/>
					</label>
					<span>product: <strong>{av * bv}</strong></span>
				</div>
				<div style={{ fontSize: '0.85em', color: '#555' }}>
					<strong>Effect log</strong> (explicit deps: [a, b]):
					<ul style={{ margin: '0.25rem 0 0', paddingLeft: '1.2rem' }}>
						{entries.map((e, i) => <li key={i}>{e}</li>)}
					</ul>
				</div>
			</div>
		);
	}
}

// demo/src/components/WatchExplicitDemo.tsx
import React, { useEffect, useRef } from 'react';
import { signal, watchEffect } from '../lib';
import { useSignalValue } from '../hooks/useSignal';

const a = signal(1);
const b = signal(10);
const log = signal<string[]>([]);

export function WatchExplicitDemo() {
  const aVal = useSignalValue(a);
  const bVal = useSignalValue(b);
  const logVal = useSignalValue(log);
  const stopRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    stopRef.current = watchEffect([a, b] as const, ([av, bv]) => {
      const entry = `${av} + ${bv} = ${(av as number) + (bv as number)}`;
      log.set([...log.get().slice(-4), entry]);
    });
    return () => {
      stopRef.current?.();
      stopRef.current = null;
      log.set([]);
    };
  }, []);

  const handleDispose = () => {
    stopRef.current?.();
    stopRef.current = null;
    log.set([...logVal, '(disposed)']);
  };

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.5rem' }}>
        <span style={{ minWidth: '40px' }}>a: {aVal}</span>
        <button onClick={() => a.set(aVal + 1)}>a++</button>
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '0.5rem' }}>
        <span style={{ minWidth: '40px' }}>b: {bVal}</span>
        <button onClick={() => b.set(bVal + 10)}>b+=10</button>
      </div>
      <div style={{ marginTop: '0.5rem' }}>
        <strong>Effect log</strong> (last 5 runs):
        {logVal.length === 0
          ? <p style={{ fontSize: '0.85em', color: '#555', margin: '0.25rem 0' }}>— increment a or b to trigger —</p>
          : logVal.map((entry, i) => (
            <p key={i} style={{ fontSize: '0.85em', color: '#555', margin: '0.25rem 0' }}>{entry}</p>
          ))}
      </div>
      <button style={{ marginTop: '0.5rem' }} onClick={handleDispose}>
        dispose effect
      </button>
    </div>
  );
}
